# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ansys.grpc.dpf.base_pb2 as base__pb2
import ansys.grpc.dpf.cyclic_support_pb2 as cyclic__support__pb2


class CyclicSupportServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_unary(
        '/ansys.api.dpf.cyclic_support.v0.CyclicSupportService/List',
        request_serializer=cyclic__support__pb2.CyclicSupport.SerializeToString,
        response_deserializer=cyclic__support__pb2.ListResponse.FromString,
        )
    self.GetExpandedIds = channel.unary_unary(
        '/ansys.api.dpf.cyclic_support.v0.CyclicSupportService/GetExpandedIds',
        request_serializer=cyclic__support__pb2.GetExpandedIdsRequest.SerializeToString,
        response_deserializer=cyclic__support__pb2.GetExpandedIdsResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/ansys.api.dpf.cyclic_support.v0.CyclicSupportService/Delete',
        request_serializer=cyclic__support__pb2.CyclicSupport.SerializeToString,
        response_deserializer=base__pb2.Empty.FromString,
        )


class CyclicSupportServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetExpandedIds(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CyclicSupportServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=cyclic__support__pb2.CyclicSupport.FromString,
          response_serializer=cyclic__support__pb2.ListResponse.SerializeToString,
      ),
      'GetExpandedIds': grpc.unary_unary_rpc_method_handler(
          servicer.GetExpandedIds,
          request_deserializer=cyclic__support__pb2.GetExpandedIdsRequest.FromString,
          response_serializer=cyclic__support__pb2.GetExpandedIdsResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=cyclic__support__pb2.CyclicSupport.FromString,
          response_serializer=base__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.dpf.cyclic_support.v0.CyclicSupportService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
