
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-22T18:52:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a65976bdfdfe41a0c249c065bf0e873373dfe4ae",
 "version": "0.0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
