# coding: utf-8

"""
    ArcGIS Earth Automation API

    This is an ArcGIS Earth Automation API help page of Swagger. You can find out more about ArcGIS Earth Automation API at https://doc.arcgis.com/en/arcgis-earth/automation-api/get-started.htm  # noqa: E501

    OpenAPI spec version: 1.16-Alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

with open('README.md','r',encoding='utf-8') as f:
    long_description = f.read()

from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil", "requests", "od"]

setup(
    name="earth_api",
    version="0.0.5",
    description="ArcGIS Earth Automation API",
    author_email="",
    url="",
    keywords=["Swagger", "ArcGIS Earth Automation API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description=long_description,
    long_description_content_type = 'text/markdown'
)