
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-22T09:35:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfc01e0fd7ad5f2df454b7715bf8b297dd40c6a2",
 "version": "0.11.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
