# Generated by Django 3.2.14 on 2022-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_infotext', '0003_infotext_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
