
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-23T15:25:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c4d27347d6ab9107431b110ac2a0077b2a0b6c1",
 "version": "2.7.0-rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
