# This file is automatically generated by setup.py
short_version = "3.0.5"
version = "3.0.5"
full_version = "3.0.5.dev-3d02890"
git_revision = "3d02890572c7377cdc7161a05383cd9556c5100a"
release = False

if not release:
    version = full_version
