from setuptools import setup

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    name='helloworld_test_rv',
    version='0.0.1',
    description='A simple hello world testing app.',
    py_modules=["helloworld_test_rv"],
    package_dir={'': 'src'},
    install_requires = [
        "blessings",],
        
    #     aiohttp,
    #     aiosignal==1.2.0,
    #     analytics-python==1.4.0,
    #     anyio==3.6.1,
    #     async-timeout==4.0.2,
    #     asynctest==0.13.0,
    #     attrs==21.4.0,
    #     backoff==1.10.0,
    #     bcrypt==3.2.2,
    #     certifi==2022.6.15,
    #     cffi==1.15.0,
    #     charset-normalizer==2.0.12,
    #     click==8.0.4,
    #     colorama==0.4.5,
    #     cryptography==37.0.2,
    #     cycler==0.11.0,
    #     fastapi==0.78.0,
    #     ffmpy==0.3.0,
    #     fonttools==4.27.1,
    #     frozenlist==1.2.0,
    #     fsspec==2022.1.0,
    #     gradio==3.0.12,
    #     h11==0.13.0,
    #     idna==3.3,
    #     importlib-metadata==4.8.3,
    #     Jinja2==3.0.3,
    #     joblib==1.1.0,
    #     kiwisolver==1.3.1,
    #     linkify-it-py==1.0.3,
    #     markdown-it-py==2.0.1,
    #     MarkupSafe==2.0.1,
    #     matplotlib==3.3.4,
    #     mdit-py-plugins==0.3.0,
    #     mdurl==0.1.0,
    #     monotonic==1.6,
    #     multidict==5.2.0,
    #     numpy==1.21.6,
    #     opencv-python==4.6.0.66,
    #     orjson==3.6.1,
    #     packaging==21.3,
    #     pandas==1.1.5,
    #     paramiko==2.11.0,
    #     Pillow==8.4.0,
    #     pycparser==2.21,
    #     pycryptodome==3.15.0,
    #     pydantic==1.9.1,
    #     pydub==0.25.1,
    #     PyNaCl==1.5.0,
    #     pyparsing==3.0.9,
    #     python-dateutil==2.8.2,
    #     python-multipart==0.0.5,
    #     pytz==2022.1,
    #     requests==2.27.1,
    #     scikit-learn==0.24.2,
    #     scipy==1.5.4,
    #     six==1.16.0,
    #     sniffio==1.2.0,
    #     starlette==0.19.1,
    #     threadpoolctl==3.1.0,
    #     typing_extensions==4.1.1,
    #     uc-micro-py==1.0.1,
    #     urllib3==1.26.9,
    #     uvicorn==0.17.0,
    #     yarl==1.7.2,
    #     zipp==3.6.0,
    # ],
    extras_require={
        "dev": [
            "pytest >= 3.7",
            "check-manifest",
            "twine"
        ]
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent"
    ],
    python_requires='>=3',
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Author",
    author_email="author@gmail.com"
#     url="https://github.com/DeoLukamba/halimo"
)
