
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-11T15:14:29-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9950c4dfb87b9ffd975ef1575b573b93aa8c8ad8",
 "version": "1.0.2.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
