list_capitals = [""""""
                 'Kabul',
                 'Tirana',
                 'Algiers',
                 'Andorra de le Vella',
                 'Luanda',
                 "Saint John's",
                 'Buenos Aires',
                 'Yerevan',
                 'Canberra',
                 'Vienna',
                 'Baku',
                 'Nassau',
                 'Manama',
                 'Dhaka',
                 'Bridgetown',
                 'Minsk',
                 'Brussels',
                 'Belmopan',
                 'Porto-Novo',
                 'Thimphu',
                 "Sucre", # More than one solved Twice
                 'Sarajevo',
                 'Gavorone',
                 'Brasilia',
                 'Banvar Seri Begawan',
                 'Sofia',
                 'Ouagadougou',
                 'Gitega',
                 'Phnom Penh',
                 'Yaounde',
                 'Ottowa',
                 'Praia',
                 'Bangui',
                 "N'djamena",
                 'Santiago',
                 'Beijing',
                 'Bogota',
                 'Moroni Comoros',
                 'Brazzaville',
                 'Kinshasa',
                 'San Jose',
                 'Zagreb',
                 'Havana',
                 'Nicosia',
                 'Prague',
                 'Copenhagen',
                 'Djibouti',
                 'Roseau',
                 'Santo Domingo',
                 'Dili',
                 'Quito',
                 'Cairo',
                 'San Salvador',
                 'Malabo',
                 'Asmara',
                 'Tallinn',
                 'Addis Ababa',
                 'Suva',
                 'Helsinki',
                 'Paris',
                 'Libreville',
                 'Banjul',
                 'Tblisi',
                 'Berlin',
                 'Accra',
                 'Athens',
                 "Saint George's",
                 'Guatemala City',
                 'Conakry',
                 'Bissau',
                 'George Town',
                 'Port-Au-Prince',
                 'Tegucigalpa',
                 'Budapest',
                 'Reykjavik',
                 'New Delhi',
                 'Jakarta',
                 'Tehran',
                 'Baghdad',
                 'Dublin',
                 'Jerusalem',
                 'Rome',
                 'Yamoussoukro',
                 'Kingston',
                 'Tokyo',
                 'Amman',
                 'Nur-Sultan',
                 'Nairobi',
                 'Tarawa',
                 'Pyongyang',
                 'Seoul',
                 'Pristina',
                 'Kuwait City',
                 'Bishkek',
                 'Vientiane',
                 'Riga',
                 'Beirut',
                 'Maseru',
                 'Monrovia',
                 'Tripoli',
                 'Vaduz',
                 'Vilnius',
                 'Luxembourg',
                 'Skopje',
                 'Antananarivo',
                 'Lilongwe',
                 'Kuala Lumpur',
                 'Male',
                 'Bamako',
                 'Valleta',
                 'Delap-Uliga-Djarrit',
                 'Nouakchott',
                 'Port Louis',
                 'Mexico City',
                 'Palikir',
                 'Chisinau',
                 'Monaco',
                 'Ulaanbaatar',
                 'Podgorica',
                 'Rabat',
                 'Maputo',
                 'Naypyitaw',
                 'Windhoek',
                 'Yaren District',
                 'Kathmandu',
                 'Amsterdam',
                 'Wellington',
                 'Managua',
                 'Niamey',
                 'Abuja',
                 'Oslo',
                 'Muscat',
                 'Islamabad',
                 'Melekeok', #More than one solved
                 'Panama City',
                 'Port Moresby',
                 'Asuncion',
                 'Lima',
                 'Manila',
                 'Warsaw',
                 'Lisbon',
                 'Doha',
                 'Bucharest',
                 'Moscow',
                 'Kigali',
                 'Basseterre',
                 'Castries',
                 'Kingstown',
                 'Apia',
                 'San Marino',
                 'Sao Tome',
                 'Riyadh',
                 'Dakar',
                 'Belgrade',
                 'Victoria',
                 'Freetown',
                 'Singapore',
                 'Bratislava',
                 'Ljubljana',
                 'Honiara',
                 'Mogadishu',
                 'Cape Town', #More than one solved Twice
                 'Juba',
                 'Madrid',
                 'Colombo', #More than one solved Twice
                 'Khartoum',
                 'Paramaribo',
                 'Mbabane', #More than one solved Twice
                 'Stockholm',
                 'Bern',
                 'Damascus',
                 'Taipei',
                 'Dushanbe',
                 'Dodoma',
                 'Bangkok',
                 'Lome',
                 "Nuku'alofa",
                 'Port of Spain',
                 'Tunis',
                 'Ankara',
                 'Ashgabat',
                 'Funafuti',
                 'Kampala',
                 'Kyiv',
                 'Abu Dhabi',
                 'London',
                 'Washington D.C.',
                 'Montevideo',
                 'Tashkent',
                 'Port Vila',
                 'Vatican City',
                 'Caracas',
                 'Hanoi',
                 "Sana'a",
                 'Lusaka',
                 'Harare',
                 ]

list_countries = [""""""'Afghanistan',
                  "Albania",
                  "Algeria",
                  "Andorra",
                  "Angola",
                  "Antigua & Barbuda",
                  "Argentina",
                  "Armenia",
                  "Australia",
                  "Austria",
                  "Azerbaijan",
                  "Bahamas",
                  "Bahrain",
                  "Bangladesh",
                  "Barbados",
                  "Belarus",
                  "Belgium",
                  "Belize",
                  "Benin",
                  "Bhutan",
                  "Bolivia",
                  "Bosnia Herzegovina",
                  "Botswana",
                  "Brazil",
                  "Brunei",
                  "Bulgaria",
                  "Burkina Faso",
                  "Burundi",
                  "Cambodia",
                  "Cameroon",
                  "Canada",
                  "Cape Verde",
                  "Central African Rep",
                  "Chad",
                  "Chile",
                  "China",
                  "Colombia",
                  "Comoros",
                  "Republic of the Congo",
                  "Democratic Republic of the Congo",
                  "Costa Rica",
                  "Croatia",
                  "Cuba",
                  "Cyprus",
                  "Czech Republic",
                  "Denmark",
                  "Djibouti",
                  "Dominica",
                  "Dominican Republic",
                  "East Timor",
                  "Ecuador",
                  "Egypt",
                  "El Salvador",
                  "Equatorial Guinea",
                  "Eritrea",
                  "Estonia",
                  "Ethiopia",
                  "Fiji",
                  "Finland",
                  "France",
                  "Gabon",
                  "Gambia",
                  "Georgia",
                  "Germany",
                  "Ghana",
                  "Greece",
                  "Grenada",
                  "Guatemala",
                  "Guinea",
                  "Guinea-Bissau",
                  "Guyana",
                  "Haiti",
                  "Honduras",
                  "Hungary",
                  "Iceland",
                  "India",
                  "Indonesia",
                  "Iran",
                  "Iraq",
                  "Ireland {Republic}",
                  "Israel",
                  "Italy",
                  "Ivory Coast",
                  "Jamaica",
                  "Japan",
                  "Jordan",
                  "Kazakhstan",
                  "Kenya",
                  "Kiribati",
                  "Korea North",
                  "Korea South",
                  "Kosovo",
                  "Kuwait",
                  "Kyrgyzstan",
                  "Laos",
                  "Latvia",
                  "Lebanon",
                  "Lesotho",
                  "Liberia",
                  "Libya",
                  "Liechtenstein",
                  "Lithuania",
                  "Luxembourg",
                  "Macedonia",
                  "Madagascar",
                  "Malawi",
                  "Malaysia",
                  "Maldives",
                  "Mali",
                  "Malta",
                  "Marshall Islands",
                  "Mauritania",
                  "Mauritius",
                  "Mexico",
                  "Micronesia",
                  "Moldova",
                  "Monaco",
                  "Mongolia",
                  "Montenegro",
                  "Morocco",
                  "Mozambique",
                  "Myanmar",
                  "Namibia",
                  "Nauru",
                  "Nepal",
                  "Netherlands",
                  "New Zealand",
                  "Nicaragua",
                  "Niger",
                  "Nigeria",
                  "Norway",
                  "Oman",
                  "Pakistan",
                  "Palau",
                  "Panama",
                  "Papua New Guinea",
                  "Paraguay",
                  "Peru",
                  "Philippines",
                  "Poland",
                  "Portugal",
                  "Qatar",
                  "Romania",
                  "Russia",
                  "Rwanda",
                  "St Kitts & Nevis",
                  "St Lucia",
                  "Saint Vincent & the Grenadines",
                  "Samoa",
                  "San Marino",
                  "Sao Tome & Principe",
                  "Saudi Arabia",
                  "Senegal",
                  "Serbia",
                  "Seychelles",
                  "Sierra Leone",
                  "Singapore",
                  "Slovakia",
                  "Slovenia",
                  "Solomon Islands",
                  "Somalia",
                  "South Africa",
                  "South Sudan",
                  "Spain",
                  "Sri Lanka",
                  "Sudan",
                  "Suriname",
                  "Swaziland",
                  "Sweden",
                  "Switzerland",
                  "Syria",
                  "Taiwan",
                  "Tajikistan",
                  "Tanzania",
                  "Thailand",
                  "Togo",
                  "Tonga",
                  "Trinidad & Tobago",
                  "Tunisia",
                  "Turkey",
                  "Turkmenistan",
                  "Tuvalu",
                  "Uganda",
                  "Ukraine",
                  "United Arab Emirates",
                  "United Kingdom",
                  "United States",
                  "Uruguay",
                  "Uzbekistan",
                  "Vanuatu",
                  "Vatican City",
                  "Venezuela",
                  "Vietnam",
                  "Yemen",
                  "Zambia",
                  "Zimbabwe",]
easy_country_list = [""""""
                     'United States of America',
                     "United Kingdom",
                     "France",
                     "Mexico",
                     "Russia",
                     "Spain",
                     "Germany",
                     "Japan",
                     "Italy",
                     "Ireland",
                     "China",
                     "Norway",
                     "Canada",
                     "Egypt",
                     "Brazil",
                     "Portugal",
                     "Australia",
                     "Greece",
                     "Finland",
                     "Sweden",
                     "India",
                     "Argentina",
                     "Belgium",
                     "Denmark",
                     "Netherlands",
                     "South Korea",
                     "Austria",
                     "Peru",
                     "Poland",
                     "Cuba",
                     "New Zealand",
                     "Vatican City",
                     "Hungary",
                     "Chile",
                     "Czech Republic",
                     "Switzerland",
                     "Israel",
                     "Luxembourg",
                     "Iraq",
                     "Monaco",
                     "Turkey",
                     "Iceland",
                     "Panama",
                     "Jamaica",
                     "Ukraine",
                     "Thailand",
                     "Afghanistan",
                     "Singapore",
                     "Algeria",
                     "Iran",
                     "Columbia",
                     "Indonesia",
                     "North Korea",
                     "Bulgaria",
                     "Romania",
                     "San Marino",
                     "Tunisia",
                     "South Africa",
                     "Pakistan",
                     "Philippines",
                     "Uruguay",
                     "Belarus",
                     "Bolivia",
                     "Venezuela",
                     "El Salvador",
                     "Latvia"""]
easy_capital_list = [""""""
                     "Washington D.C. ",
                     "London",
                     "Paris",
                     "Mexico City",
                     "Moscow",
                     "Madrid",
                     "Berlin",
                     "Tokyo",
                     "Rome",
                     "Dublin",
                     "Beijing",
                     "Oslo",
                     "Ottawa",
                     "Cairo",
                     "Brasilia",
                     "Lisbon",
                     "Canberra",
                     "Athens",
                     "Helsinki",
                     "Stockholm",
                     "New Delhi",
                     "Buenos Aires",
                     "Brussels",
                     "Copenhagen",
                     "Amsterdam",
                     "Seoul",
                     "Vienna",
                     "Lima",
                     "Warsaw",
                     "Havana",
                     "Wellington",
                     "Vatican City",
                     "Budapest",
                     "Santiago",
                     "Prague",
                     "Bern",
                     "Jerusalem",
                     "Luxembourg",
                     "Baghdad",
                     "Monaco",
                     "Ankara",
                     "Reykjavik",
                     "Panama City",
                     "Kingston",
                     "Kyiv",
                     "Bangkok",
                     "Kabul",
                     "Singapore",
                     "Algiers",
                     "Tehran",
                     "Bogota",
                     "Jakarta",
                     "Pyongyang",
                     "Sofia",
                     "Bucharest",
                     "San Marino",
                     "Tunis",
                     "Cape Town",
                     "Islamabad",
                     "Manila",
                     "Montevideo",
                     "Minsk",
                     "Sucre",
                     "Caracas",
                     "San Salvador",
                     "Riga",]
moderate_capital_list = ["""""""Quito",
                         "Nairobi",
                         "Hanoi",
                         "Port-Au-Prince",
                         "Guatemala City",
                         "Zagreb",
                         "Tallinn",
                         "Tripoli",
                         "Sarajevo",
                         "Kuwait City",
                         "Taipei",
                         "Kuala Lumpur",
                         "Andorra la Vella",
                         "Abu Dhabi",
                         "Damascus",
                         "Belgrade",
                         "Rabat",
                         "Beirut",
                         "Djibouti",
                         "Bratislava",
                         "Riyadh",
                         "Kathmandu",
                         "Nassau",
                         "San Jose",
                         "Georgetown",
                         "Vilnius",
                         "Tirana",
                         "Ulaanbaatar",
                         "Addis Ababa",
                         "Dhaka",
                         "Nicosia",
                         "Asuncion",
                         "Freetown",
                         "Vaduz",
                         "Baku",
                         "Amman",
                         "Valletta",
                         "Dakar",
                         "Santo Domingo",
                         "Mogadishu",
                         "Phnom Penh",
                         "Doha",
                         "Male",
                         "Kingstown",
                         "Ljubljana",
                         "Sao Tome",
                         "Port of Spain",
                         "Skopje",
                         "Nur-Sultan",
                         "Tbilisi",
                         "Colombo",
                         "Accra",
                         "Sana'a",
                         "Muscat",
                         "Managua",
                         "Pristina",
                         "Bissau",
                         "St.John's",
                         "Khartoum",
                         "Bridgetown",
                         "Belmopan",
                         "Yerevan",
                         "Harare",
                         "Victoria",
                         "Kinshasa",
                         "Chisinau",]
moderate_country_list = [""""""
                         "Ecuador",
                         "Kenya",
                         "Vietnam",
                         "Haiti",
                         "Guatemala",
                         "Croatia",
                         "Estonia",
                         "Libya",
                         "Bosnia and Herzegovina",
                         "Kuwait",
                         "Taiwan",
                         "Malaysia",
                         "Andorra",
                         "United Arab Emirates",
                         "Syria",
                         "Serbia",
                         "Morocco",
                         "Lebanon",
                         "Djibouti",
                         "Slovakia",
                         "Saudi Arabia",
                         "Nepal",
                         "Bahamas",
                         "Costa Rica",
                         "Guyana",
                         "Lithuania",
                         "Albania",
                         "Mongolia",
                         "Ethiopia",
                         "Bangladesh",
                         "Cyprus",
                         "Paraguay",
                         "Sierra Leone",
                         "Liechtenstein",
                         "Azerbaijan",
                         "Jordan",
                         "Malta",
                         "Senegal",
                         "Dominican Republic",
                         "Somalia",
                         "Cambodia",
                         "Qatar",
                         "Maldives",
                         "Saint Vincent and the Grenadines",
                         "Slovenia",
                         "Sao Tome and Principe",
                         "Trinidad and Tobago",
                         "Macedonia",
                         "Kazakhstan",
                         "Georgia",
                         "Sri Lanka",
                         "Ghana",
                         "Yemen",
                         "Oman",
                         "Nicaragua",
                         "Kosovo",
                         "Guinea-Bissau",
                         "Antigua and Barbuda",
                         "Sudan",
                         "Barbados",
                         "Belize",
                         "Armenia",
                         "Zimbabwe",
                         "Seychelles",
                         "Democratic Republic of the Congo",
                         "Moldova",]
hard_capital_list = [""""""
                     "Luanda",
                     "Tegucigalpa",
                     "Port Moresby",
                     "Juba",
                     "St. George's",
                     "Brazzaville",
                     "Tashkent",
                     "Windhoek",
                     "Paramaribo",
                     "Dili",
                     "Podgorica",
                     "Manama",
                     "Monrovia",
                     "Suva",
                     "Antananarivo",
                     "Abuja",
                     "Vientiane",
                     "Bishkek",
                     "Libreville",
                     "Kampala",
                     "Dodoma",
                     "Kigali",
                     "Port Louis",
                     "Roseau",
                     "Porto-Novo",
                     "Lome",
                     "Ouagadougou",
                     "Thimphu",
                     "Asmara",
                     "Lusaka",
                     "Maputo",
                     "Praia",
                     "Gaborone",
                     "Ashgabat",
                     "Castries",
                     "Apia",
                     "Conakry",
                     "Basseterre",
                     "Yaounde",
                     "Dushanbe",
                     "Bamako",
                     "Bandar Seri Begawan",
                     "N'djamena",
                     "Lilongwe",
                     "Niamey",
                     "Bangui",
                     "Moroni",
                     "Banjul",
                     "Port Vila",
                     "Lobamba",
                     "Gitega",
                     "Funafuti",
                     "Maseru",
                     "Yamoussoukro",
                     "Malabo",
                     "Yaren District",
                     "Naypyidaw",
                     "Nouakchott",
                     "Honiara",
                     "Tarawa",
                     "Nukuʻalofa",
                     "Palikir",
                     "Majuro",
                     "Ngerulmud",
                     ]
hard_country_list = [""""""
                     "Angola",
                     "Honduras",
                     "Papua New Guinea",
                     "South Sudan",
                     "Grenada",
                     "Republic of the Congo",
                     "Uzbekistan",
                     "Namibia",
                     "Suriname",
                     "East Timor",
                     "Montenegro",
                     "Bahrain",
                     "Liberia",
                     "Fiji",
                     "Madagascar",
                     "Nigeria",
                     "Laos",
                     "Kyrgyzstan",
                     "Gabon",
                     "Uganda",
                     "Tanzania",
                     "Rwanda",
                     "Mauritius",
                     "Dominica",
                     "Benin",
                     "Togo",
                     "Burkina Faso",
                     "Bhutan",
                     "Eritrea",
                     "Zambia",
                     "Mozambique",
                     "Cape Verde",
                     "Botswana",
                     "Turkmenistan",
                     "Saint Lucia",
                     "Samoa",
                     "Guinea",
                     "Saint Kitts and Nevis",
                     "Cameroon",
                     "Tajikistan",
                     "Mali",
                     "Brunei",
                     "Chad",
                     "Malawi",
                     "Niger",
                     "Central African Republic",
                     "Comoros",
                     "The Gambia",
                     "Vanuatu",
                     "Swaziland",
                     "Burundi",
                     "Tuvalu",
                     "Lesotho",
                     "Ivory Coast",
                     "Equatorial Guinea",
                     "Nauru",
                     "Myanmar",
                     "Mauritania",
                     "Solomon Islands",
                     "Kiribati",
                     "Tonga",
                     "Micronesia",
                     "Marshall Islands",
                     "Palau"
                     ]