"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import intentionet.bfe.proto.datamodel.ip_primitives_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class TopologySummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HOSTNAMES_FIELD_NUMBER: builtins.int
    INTERFACE_NAMES_FIELD_NUMBER: builtins.int
    SUBNET_FIELD_NUMBER: builtins.int
    LAYER1_FIELD_NUMBER: builtins.int
    BGP_FIELD_NUMBER: builtins.int
    EIGRP_FIELD_NUMBER: builtins.int
    IPSEC_FIELD_NUMBER: builtins.int
    ISIS_FIELD_NUMBER: builtins.int
    OSPF_FIELD_NUMBER: builtins.int
    VXLAN_FIELD_NUMBER: builtins.int
    DEVICE_TYPES_FIELD_NUMBER: builtins.int
    DEVICE_MODELS_FIELD_NUMBER: builtins.int
    HUMAN_NAMES_FIELD_NUMBER: builtins.int
    HOSTNAME_DEVICE_INFO_FIELD_NUMBER: builtins.int
    @property
    def hostnames(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def interface_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def subnet(self) -> global___SubnetTopology: ...
    @property
    def layer1(self) -> global___Layer1Topology: ...
    @property
    def bgp(self) -> global___BgpTopology: ...
    @property
    def eigrp(self) -> global___EigrpTopology: ...
    @property
    def ipsec(self) -> global___IpSecTopology: ...
    @property
    def isis(self) -> global___IsIsTopology: ...
    @property
    def ospf(self) -> global___OspfTopology: ...
    @property
    def vxlan(self) -> global___VxlanTopology: ...
    @property
    def device_types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def device_models(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def human_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def hostname_device_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceInfo]: ...
    def __init__(self,
        *,
        hostnames: typing.Optional[typing.Iterable[typing.Text]] = ...,
        interface_names: typing.Optional[typing.Iterable[typing.Text]] = ...,
        subnet: typing.Optional[global___SubnetTopology] = ...,
        layer1: typing.Optional[global___Layer1Topology] = ...,
        bgp: typing.Optional[global___BgpTopology] = ...,
        eigrp: typing.Optional[global___EigrpTopology] = ...,
        ipsec: typing.Optional[global___IpSecTopology] = ...,
        isis: typing.Optional[global___IsIsTopology] = ...,
        ospf: typing.Optional[global___OspfTopology] = ...,
        vxlan: typing.Optional[global___VxlanTopology] = ...,
        device_types: typing.Optional[typing.Iterable[typing.Text]] = ...,
        device_models: typing.Optional[typing.Iterable[typing.Text]] = ...,
        human_names: typing.Optional[typing.Iterable[typing.Text]] = ...,
        hostname_device_info: typing.Optional[typing.Iterable[global___DeviceInfo]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bgp",b"bgp","eigrp",b"eigrp","ipsec",b"ipsec","isis",b"isis","layer1",b"layer1","ospf",b"ospf","subnet",b"subnet","vxlan",b"vxlan"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bgp",b"bgp","device_models",b"device_models","device_types",b"device_types","eigrp",b"eigrp","hostname_device_info",b"hostname_device_info","hostnames",b"hostnames","human_names",b"human_names","interface_names",b"interface_names","ipsec",b"ipsec","isis",b"isis","layer1",b"layer1","ospf",b"ospf","subnet",b"subnet","vxlan",b"vxlan"]) -> None: ...
global___TopologySummary = TopologySummary

class DeviceInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEVICE_TYPE_INDEX_FIELD_NUMBER: builtins.int
    DEVICE_MODEL_INDEX_FIELD_NUMBER: builtins.int
    HUMAN_NAME_INDEX_FIELD_NUMBER: builtins.int
    device_type_index: builtins.int
    device_model_index: builtins.int
    human_name_index: builtins.int
    def __init__(self,
        *,
        device_type_index: builtins.int = ...,
        device_model_index: builtins.int = ...,
        human_name_index: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["device_model_index",b"device_model_index","device_type_index",b"device_type_index","human_name_index",b"human_name_index"]) -> None: ...
global___DeviceInfo = DeviceInfo

class InterfaceRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HOSTNAME_FIELD_NUMBER: builtins.int
    INTERFACE_NAME_FIELD_NUMBER: builtins.int
    hostname: builtins.int
    interface_name: builtins.int
    def __init__(self,
        *,
        hostname: builtins.int = ...,
        interface_name: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hostname",b"hostname","interface_name",b"interface_name"]) -> None: ...
global___InterfaceRef = InterfaceRef

class SubnetTopology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBNETS_FIELD_NUMBER: builtins.int
    EDGES_FIELD_NUMBER: builtins.int
    PREFIXES_FIELD_NUMBER: builtins.int
    @property
    def subnets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SubnetId]: ...
    @property
    def edges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SubnetEdge]: ...
    @property
    def prefixes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[intentionet.bfe.proto.datamodel.ip_primitives_pb2.IpPrefix]: ...
    def __init__(self,
        *,
        subnets: typing.Optional[typing.Iterable[global___SubnetId]] = ...,
        edges: typing.Optional[typing.Iterable[global___SubnetEdge]] = ...,
        prefixes: typing.Optional[typing.Iterable[intentionet.bfe.proto.datamodel.ip_primitives_pb2.IpPrefix]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edges",b"edges","prefixes",b"prefixes","subnets",b"subnets"]) -> None: ...
global___SubnetTopology = SubnetTopology

class SubnetId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    PREFIX_FIELD_NUMBER: builtins.int
    id: typing.Text
    prefix: builtins.int
    def __init__(self,
        *,
        id: typing.Text = ...,
        prefix: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","prefix",b"prefix"]) -> None: ...
global___SubnetId = SubnetId

class SubnetEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADIFACE_FIELD_NUMBER: builtins.int
    TAILIFACE_FIELD_NUMBER: builtins.int
    TAILSUBNET_FIELD_NUMBER: builtins.int
    PREFIX_FIELD_NUMBER: builtins.int
    @property
    def headIface(self) -> global___InterfaceRef: ...
    @property
    def tailIface(self) -> global___InterfaceRef: ...
    tailSubnet: builtins.int
    prefix: builtins.int
    def __init__(self,
        *,
        headIface: typing.Optional[global___InterfaceRef] = ...,
        tailIface: typing.Optional[global___InterfaceRef] = ...,
        tailSubnet: builtins.int = ...,
        prefix: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headIface",b"headIface","tail",b"tail","tailIface",b"tailIface","tailSubnet",b"tailSubnet"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headIface",b"headIface","prefix",b"prefix","tail",b"tail","tailIface",b"tailIface","tailSubnet",b"tailSubnet"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["tail",b"tail"]) -> typing.Optional[typing_extensions.Literal["tailIface","tailSubnet"]]: ...
global___SubnetEdge = SubnetEdge

class Layer1Topology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Layer1Edge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___Layer1Edge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___Layer1Topology = Layer1Topology

class Layer1Edge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADNODE_FIELD_NUMBER: builtins.int
    TAILNODE_FIELD_NUMBER: builtins.int
    headNode: builtins.int
    tailNode: builtins.int
    def __init__(self,
        *,
        headNode: builtins.int = ...,
        tailNode: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["headNode",b"headNode","tailNode",b"tailNode"]) -> None: ...
global___Layer1Edge = Layer1Edge

class BgpTopology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BgpEdge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___BgpEdge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___BgpTopology = BgpTopology

class BgpEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADNODE_FIELD_NUMBER: builtins.int
    TAILNODE_FIELD_NUMBER: builtins.int
    headNode: builtins.int
    tailNode: builtins.int
    def __init__(self,
        *,
        headNode: builtins.int = ...,
        tailNode: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["headNode",b"headNode","tailNode",b"tailNode"]) -> None: ...
global___BgpEdge = BgpEdge

class EigrpTopology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EigrpEdge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___EigrpEdge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___EigrpTopology = EigrpTopology

class EigrpEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADNODE_FIELD_NUMBER: builtins.int
    TAILNODE_FIELD_NUMBER: builtins.int
    headNode: builtins.int
    tailNode: builtins.int
    def __init__(self,
        *,
        headNode: builtins.int = ...,
        tailNode: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["headNode",b"headNode","tailNode",b"tailNode"]) -> None: ...
global___EigrpEdge = EigrpEdge

class IpSecTopology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IpSecEdge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___IpSecEdge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___IpSecTopology = IpSecTopology

class IpSecEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADNODE_FIELD_NUMBER: builtins.int
    TAILNODE_FIELD_NUMBER: builtins.int
    headNode: builtins.int
    tailNode: builtins.int
    def __init__(self,
        *,
        headNode: builtins.int = ...,
        tailNode: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["headNode",b"headNode","tailNode",b"tailNode"]) -> None: ...
global___IpSecEdge = IpSecEdge

class IsIsTopology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IsIsEdge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___IsIsEdge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___IsIsTopology = IsIsTopology

class IsIsEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADNODE_FIELD_NUMBER: builtins.int
    TAILNODE_FIELD_NUMBER: builtins.int
    headNode: builtins.int
    tailNode: builtins.int
    def __init__(self,
        *,
        headNode: builtins.int = ...,
        tailNode: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["headNode",b"headNode","tailNode",b"tailNode"]) -> None: ...
global___IsIsEdge = IsIsEdge

class OspfTopology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OspfEdge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___OspfEdge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___OspfTopology = OspfTopology

class OspfEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADNODE_FIELD_NUMBER: builtins.int
    TAILNODE_FIELD_NUMBER: builtins.int
    headNode: builtins.int
    tailNode: builtins.int
    def __init__(self,
        *,
        headNode: builtins.int = ...,
        tailNode: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["headNode",b"headNode","tailNode",b"tailNode"]) -> None: ...
global___OspfEdge = OspfEdge

class RipTopology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RipEdge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___RipEdge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___RipTopology = RipTopology

class RipEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADNODE_FIELD_NUMBER: builtins.int
    TAILNODE_FIELD_NUMBER: builtins.int
    headNode: builtins.int
    tailNode: builtins.int
    def __init__(self,
        *,
        headNode: builtins.int = ...,
        tailNode: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["headNode",b"headNode","tailNode",b"tailNode"]) -> None: ...
global___RipEdge = RipEdge

class VxlanTopology(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VxlanEdge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___VxlanEdge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___VxlanTopology = VxlanTopology

class VxlanEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADNODE_FIELD_NUMBER: builtins.int
    TAILNODE_FIELD_NUMBER: builtins.int
    headNode: builtins.int
    tailNode: builtins.int
    def __init__(self,
        *,
        headNode: builtins.int = ...,
        tailNode: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["headNode",b"headNode","tailNode",b"tailNode"]) -> None: ...
global___VxlanEdge = VxlanEdge
