# Generated by Django 2.2.26 on 2022-01-20 15:10

from django.db import migrations, models
import djangoldp.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom du projet')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Illustration du projet')),
                ('presentation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Présentation du projet')),
                ('visible', models.BooleanField(blank=True, default=False, null=True, verbose_name='Visible sur le site')),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view', 'control'],
                'depth': 0,
            },
        ),
    ]
