# Generated by Django 2.2.26 on 2022-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hiphopcommunity', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='society',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='société'),
        ),
    ]
