# Generated by Django 2.2.26 on 2022-06-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hiphopcommunity', '0017_auto_20220503_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campain',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control'], 'verbose_name': 'Suivi'},
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Url de contact'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Url de contact'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='campain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoldp_hiphopcommunity.Campain', verbose_name='suivi'),
        ),
    ]
