# Generated by Django 2.2.26 on 2022-06-10 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hiphopcommunity', '0018_auto_20220606_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Visible sur le site'),
        ),
    ]
