
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-27T16:36:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "556fb58d0965292a0d2ae2a7fc16249a7d0fa5d1",
 "version": "6.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
