
elem = {
    "Home": '//*[@id="MainMap"]/div[1]',
    "Menu": '//*[@id="MainMap"]/div[2]',
    "OneTouch": '//*[@id="MainMap"]/div[3]',
    "Help": '//*[@id="MainMap"]/div[4]',
    "Back": '//*[@id="MainMap"]/div[5]',
    "Status": '//*[@id="MainMap"]/div[6]',
    "Filter Pump Home": '//*[@id="1_24_0"]',
    "Temp1 Home": '//*[@id="1_24_1"]',
    "Spa Home": '//*[@id="1_24_1"]',
    "Temp2 Home": '//*[@id="1_24_2"]',
    "Cleaner Home": '//*[@id="1_24_3"]',
    "Low Speed Home": '//*[@id="1_24_4"]',
    "Aux3 Home": '//*[@id="1_24_5"]',
    "OneTouch 3 Home": '//*[@id="1_24_6"]',
    "Other Devices": '//*[@id="1_24_7"]',
    "Schedule": '//*[@id="15_24_0"]',
    "Customize Home": '//*[@id="15_24_1"]',
    "Program Group": '//*[@id="15_24_2"]',
    "Set Temp": '//*[@id="15_24_3"]',
    "System Setup": '//*[@id="15_24_4"]',
    "Set Date/Time": '//*[@id="15_24_6"]',
    "Lockouts Password": '//*[@id="15_24_7"]',
    "Set AquaPure": '//*[@id="15_24_8"]',
    "Add Schedule": '//*[@id="40_24_0"]',
    "Edit Schedule": '//*[@id="40_24_1"]',
    "Delete Schedule": '//*[@id="40_24_2"]',
    "Page Down Schedule": '//*[@id="40_24_3"]',
    "Page Up Schedule": '//*[@id="40_24_4"]',
    "Save Schedule": '//*[@id="40_24_5"]',
    "Schedule All Days": '//*[@id="40_24_6"]',
    "Schedule Monday": '//*[@id="40_24_7"]',
    "Schedule Tuesday": '//*[@id="40_24_8"]',
    "Schedule Wednesday": '//*[@id="40_24_9"]',
    "Schedule Thursday": '//*[@id="40_24_10"]',
    "Schedule Friday": '//*[@id="40_24_11"]',
    "Schedule Saturday": '//*[@id="40_24_12"]',
    "Schedule Sunday": '//*[@id="40_24_13"]',
    "Schedule Weekdays": '//*[@id="40_24_14"]',
    "Schedule Weekends": '//*[@id="40_24_15"]',
    "Start Time Schedule": '//*[@id="40_24_16"]',
    "Stop Time Schedule": '//*[@id="40_24_17"]',
    "Set Temp Temp1": '//*[@id="57_24_0"]',
    "Set Temp Temp2": '//*[@id="57_24_2"]',
    "Page1 Left Arrow": '//*[@id="20_24_12"]',
    "Page1 Right Arrow": '//*[@id="20_24_13"]',
    "VSP Setup": '//*[@id="20_24_0"]',
    "Label Aux": '//*[@id="20_24_1"]',
    "Color Lights": '//*[@id="20_24_2"]',
    "Esp Link": '//*[@id="20_24_3"]',
    "Dimmers": '//*[@id="20_24_4"]',
    "OneTouch Setup": '//*[@id="20_24_5"]',
    "Spa Remotes": '//*[@id="20_24_6"]',
    "Sprinkler Setup": '//*[@id="20_24_7"]',
    "Device Runtime": '//*[@id="20_24_8"]',
    "Maintain Temp": '//*[@id="20_24_9"]',
    "RS Interlink": '//*[@id="20_24_10"]',
    "Freeze Protection": '//*[@id="20_24_11"]',
    "Heat Pump": '//*[@id="73_24_0"]',
    "HP Priority": '//*[@id="73_24_1"]',
    "Slr Priority": '//*[@id="73_24_2"]',
    "Assign JVAs": '//*[@id="73_24_3"]',
    "Dusk Set Up": '//*[@id="73_24_4"]',
    "All Off Time": '//*[@id="73_24_5"]',
    "PLockOut": '//*[@id="73_24_6"]',
    "DST": '//*[@id="73_24_7"]',
    "Product Info": '//*[@id="73_24_8"]',
    "Air Temp": '//*[@id="73_24_9"]',
    "Temp Calibrate": '//*[@id="73_24_10"]',
    "Degrees": '//*[@id="73_24_11"]',
    "Page2 Left Arrow": '//*[@id="73_24_12"]',
    "Page2 Right Arrow": '//*[@id="73_24_13"]',
    "In-Floor": '//*[@id="74_24_0"]',
    "Clear Memory": '//*[@id="74_24_1"]',
    "Cancel Delay": '//*[@id="74_24_2"]',
    "Chemlink": '//*[@id="74_24_3"]',
    "Cover-Pools": '//*[@id="74_24_4"]',
    "Smart JVS": '//*[@id="74_24_5"]',
    "About": '//*[@id="74_24_6"]',
    "Page3 Left Arrow": '//*[@id="74_24_12"]',
    "Page3 Right Arrow": '//*[@id="74_24_13"]',
    "0": '//*[@id="time_pad"]/div[11]',
    "1": '//*[@id="time_pad"]/div[8]',
    "2": '//*[@id="time_pad"]/div[9]',
    "3": '//*[@id="time_pad"]/div[10]',
    "4": '//*[@id="time_pad"]/div[5]',
    "5": '//*[@id="time_pad"]/div[6]',
    "6": '//*[@id="time_pad"]/div[7]',
    "7": '//*[@id="time_pad"]/div[2]',
    "8": '//*[@id="time_pad"]/div[3]',
    "9": '//*[@id="time_pad"]/div[4]',
    "AM/PM": '//*[@id="41_25_2"]',
    "timeEnter": '//*[@id="time_pad"]/div[13]',
    'SAM': '//*[@id="72_24_0"]',
    'Party': '//*[@id="72_24_1"]',
    'Romance': '//*[@id="72_24_2"]',
    'Caribbean': '//*[@id="72_24_3"]',
    'American': '//*[@id="72_24_4"]',
    'Cal Sunset': '//*[@id="72_24_5"]',
    'Royal': '//*[@id="72_24_6"]',
    'Blue': '//*[@id="72_24_7"]',
    'Green': '//*[@id="72_24_8"]',
    'Red': '//*[@id="72_24_9"]',
    'White': '//*[@id="72_24_10"]',
    'Magenta Pentair': '//*[@id="72_24_11"]',
    'Alpine White': '//*[@id="72_24_0"]',
    'Sky Blue': '//*[@id="72_24_1"]',
    'Cobalt Blue': '//*[@id="72_24_2"]',
    'Caribbean Blue': '//*[@id="72_24_3"]',
    'Spring Green': '//*[@id="72_24_4"]',
    'Emerald Green': '//*[@id="72_24_5"]',
    'Emerald Rose': '//*[@id="72_24_6"]',
    'Magenta': '//*[@id="72_24_7"]',
    'Violet': '//*[@id="72_24_8"]',
    'Slow': '//*[@id="72_24_9"]',
    'Fast': '//*[@id="72_24_10"]',
    'USA Jandy': '//*[@id="72_24_11"]',
    'Fat Tuesday': '//*[@id="72_24_12"]',
    'Disco Tech': '//*[@id="72_24_13"]',
    'Voodo': '//*[@id="72_24_0"]',
    'Deep Blue Sea': '//*[@id="72_24_1"]',
    'Royal Blue': '//*[@id="72_24_2"]',
    'Afternoon Skies': '//*[@id="72_24_3"]',
    'Aqua Green': '//*[@id="72_24_4"]',
    'Emerald': '//*[@id="72_24_5"]',
    'Cloud White': '//*[@id="72_24_6"]',
    'Warm Red': '//*[@id="72_24_7"]',
    'Flamingo': '//*[@id="72_24_8"]',
    'Vivid Violet': '//*[@id="72_24_9"]',
    'Sangria': '//*[@id="72_24_10"]',
    'Twilight': '//*[@id="72_24_11"]',
    'Tranquility': '//*[@id="72_24_12"]',
    'Gemstone': '//*[@id="72_24_13"]',
    'USA': '//*[@id="72_24_14"]',
}

lights = {
    'pentair': 'Pentair\nIntelliBrite',
    'jandy': 'Jandy LED\nWaterColors',
    'hayward': 'Hayward\nUniversal',
    'jandyColors': 'JandyColors',
    'pentairSAm/SAL': 'Pentair\nSAm/SAL'
}

abbreviations = {
    'pentair': 'IB',
    'jandy': 'JL',
    'hayward': 'HU',
}

colors = {
    'pentair': ['SAM', 'Party', 'Romance', 'Caribbean', 'American', 'Cal Sunset', 'Royal', 'Blue', 'Green', 'Red', 'White', 'Magenta Pentair'],
    'jandy': ['Alpine White', 'Sky Blue', 'Cobalt Blue', 'Caribbean Blue', 'Spring Green', 'Emerald Green', 'Emerald Rose', 'Magenta', 'Violet', 'Slow', 'Fast', 'USA Jandy', 'Fat Tuesday', 'Disco Tech'],
    'hayward': ['Voodo', 'Deep Blue Sea', 'Royal Blue', 'Afternoon Skies', 'Aqua Green', 'Emerald', 'Cloud White', 'Warm Red', 'Flamingo', 'Vivid Violet', 'Sangria', 'Twilight', 'Tranquility', 'Gemstone', 'USA'],
}

sequences = {
    'SAM': ['Red', 'Green', 'Blue', 'Red', 'Red'],
    'Party': ['Red', 'Green', 'Blue', 'Violet'],
    'Romance': ['Red', 'Green', 'Blue', 'Blue', 'Blue', 'Red'],
    'Caribbean': ['Blue', 'Green', 'Green', 'Blue', 'Blue'],
    'American': ['Orange', 'Red', 'Blue', 'Orange'],
    'Cal Sunset': ['Orange', 'Orange', 'Red', 'Red', 'Orange'],
    'Royal': ['Blue'],
    'Blue': ['Blue'],
    'Green': ['Green'],
    'Red': ['Orange'],
    'White': ['Undefined'],
    'Magenta Pentair': ['Red'],
    'Alpine White': ['Undefined'],
    'Sky Blue': ['Blue'],
    'Cobalt Blue': ['Blue'],
    'Caribbean Blue': ['Green'],
    'Spring Green': ['Green'],
    'Emerald Green': ['Green'],
    'Emerald Rose': ['Orange'],
    'Magenta': ['Red'],
    'Violet': ['Red'],
    'Slow': ['Blue', 'Blue', 'Green', 'Green', 'Orange', 'Red', 'Red', 'Red', 'Blue'],
    'Fast': ['Blue', 'Blue', 'Light Green', 'Green', 'Orange', 'Light Green', 'Red', 'Red', 'Blue'],
    'USA Jandy': ['Undefined', 'Red', 'Blue'],
    'Fat Tuesday': ['Blue', 'Red', 'Red', 'Blue'],
    'Disco Tech': ['Blue', 'Green', 'Red', 'Blue'],
    'Voodo': ['Blue', 'Red', 'Red', 'Violet'],
    'Deep Blue Sea': ['Blue'],
    'Royal Blue': ['Blue'],
    'Afternoon Skies': ['Blue'],
    'Aqua Green': ['Green'],
    'Emerald': ['Green'],
    'Cloud White': ['Light Green'],
    'Warm Red': ['Red'],
    'Flamingo': ['Red'],
    'Vivid Violet': ['Red'],
    'Sangria': ['Red'],
    'Twilight': ['Violet', 'Green', 'Blue', 'Blue', 'Red', 'Red', 'Violet'],
    'Tranquility': ['Blue', 'Red', 'Blue', 'Blue'],
    'Gemstone': ['Green', 'Blue', 'Red'],
    'USA': ['Red', 'Green', 'Blue'],
}

times = {
    'SAM': [10.5,30,15,6,8],
    'Party': [10.5,2,1.5,1],
    'Romance': [14,25,45,11,8,15],
    'Caribbean': [19,13,12,13,3],
    'American': [16,8,7,15],
    'Cal Sunset': [17,14,12,14,13],
    'Royal': [18],
    'Blue': [22],
    'Green': [25],
    'Red': [25],
    'White': [25],
    'Magenta Pentair': [28],
    'Alpine White': [13.5],
    'Sky Blue': [14],
    'Cobalt Blue': [19],
    'Caribbean Blue': [23],
    'Spring Green': [29],
    'Emerald Green': [31],
    'Emerald Rose': [35],
    'Magenta': [38],
    'Violet': [43],
    'Slow': [46,15,15,39,15,24,19,10,28],
    'Fast': [49,4,6,6,6,3,4,4,6],
    'USA Jandy': [55,7,8],
    'Fat Tuesday': [57,3,5,10],
    'Disco Tech': [60.75,0.5,0.23,0.28],
    'Voodo': [32,0.25,0.25,0.35],
    'Deep Blue Sea': [20],
    'Royal Blue': [25],
    'Afternoon Skies': [29],
    'Aqua Green': [32],
    'Emerald': [34],
    'Cloud White': [38],
    'Warm Red': [41],
    'Flamingo': [46],
    'Vivid Violet': [47],
    'Sangria': [54],
    'Twilight': [55,7,6,10,10,12,8],
    'Tranquility': [54,20,17,5],
    'Gemstone': [60,7,8],
    'USA': [61,7,5],
}



#iterations = {
#    'pentair': '',
#    'jandy': '',
#    'hayward': '',
#}
