
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "af3064f053d28a14251a91c0492006234db4130c",
 "version": "5.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
