
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-24T19:36:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "698ba5decd557781b32e7219ef172d71d86fb189",
 "version": "2022.7.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
