
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-20T15:29:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "04057e19deee4b1b49d2108265262d2037be2cda",
 "version": "4.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
