
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-25T03:22:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "80cdf126e1b42ca41f0b652247a2a553e4f570f5",
 "version": "1.17.0.post.dev66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
