
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-26T12:48:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2f1ce2266055aa2885837ef9e383df56c0aed9e",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
