"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import intentionet.bfe.proto.assertions.flow_pb2
import intentionet.bfe.proto.assertions.parameters_pb2
import intentionet.bfe.proto.assertions.violations_pb2
import intentionet.bfe.proto.datamodel.range_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ServiceAccessibilityAssertionInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOURCE_FIELD_NUMBER: builtins.int
    SERVICES_FIELD_NUMBER: builtins.int
    SOURCE_GROUPS_FIELD_NUMBER: builtins.int
    @property
    def source(self) -> global___SourceExpr: ...
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServiceExpr]: ...
    @property
    def source_groups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SourceGroup]: ...
    def __init__(self,
        *,
        source: typing.Optional[global___SourceExpr] = ...,
        services: typing.Optional[typing.Iterable[global___ServiceExpr]] = ...,
        source_groups: typing.Optional[typing.Iterable[global___SourceGroup]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["source",b"source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["services",b"services","source",b"source","source_groups",b"source_groups"]) -> None: ...
global___ServiceAccessibilityAssertionInput = ServiceAccessibilityAssertionInput

class ServiceAccessibilityAssertionResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Violator(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SERVICE_NAME_FIELD_NUMBER: builtins.int
        DESCRIPTION_INDEX_FIELD_NUMBER: builtins.int
        ALL_FLOWS_FAIL_FIELD_NUMBER: builtins.int
        SOME_SOURCES_FAIL_FIELD_NUMBER: builtins.int
        SOME_FLOWS_FAIL_FIELD_NUMBER: builtins.int
        SOME_PATHS_FAIL_FIELD_NUMBER: builtins.int
        service_name: typing.Text
        @property
        def description_index(self) -> intentionet.bfe.proto.assertions.violations_pb2.DescriptionIndex: ...
        @property
        def all_flows_fail(self) -> global___ServiceAccessibilityAssertionResult.AllFlowsFail: ...
        @property
        def some_sources_fail(self) -> global___ServiceAccessibilityAssertionResult.SomeSourcesFail: ...
        @property
        def some_flows_fail(self) -> global___ServiceAccessibilityAssertionResult.SomeFlowsFail: ...
        @property
        def some_paths_fail(self) -> global___ServiceAccessibilityAssertionResult.SomePathsFail: ...
        def __init__(self,
            *,
            service_name: typing.Text = ...,
            description_index: typing.Optional[intentionet.bfe.proto.assertions.violations_pb2.DescriptionIndex] = ...,
            all_flows_fail: typing.Optional[global___ServiceAccessibilityAssertionResult.AllFlowsFail] = ...,
            some_sources_fail: typing.Optional[global___ServiceAccessibilityAssertionResult.SomeSourcesFail] = ...,
            some_flows_fail: typing.Optional[global___ServiceAccessibilityAssertionResult.SomeFlowsFail] = ...,
            some_paths_fail: typing.Optional[global___ServiceAccessibilityAssertionResult.SomePathsFail] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["all_flows_fail",b"all_flows_fail","description_index",b"description_index","problem",b"problem","some_flows_fail",b"some_flows_fail","some_paths_fail",b"some_paths_fail","some_sources_fail",b"some_sources_fail"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["all_flows_fail",b"all_flows_fail","description_index",b"description_index","problem",b"problem","service_name",b"service_name","some_flows_fail",b"some_flows_fail","some_paths_fail",b"some_paths_fail","some_sources_fail",b"some_sources_fail"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["problem",b"problem"]) -> typing.Optional[typing_extensions.Literal["all_flows_fail","some_sources_fail","some_flows_fail","some_paths_fail"]]: ...

    class Conformer(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SERVICE_NAME_FIELD_NUMBER: builtins.int
        FLOW_FIELD_NUMBER: builtins.int
        SUCCESS_SUMMARY_FIELD_NUMBER: builtins.int
        service_name: typing.Text
        @property
        def flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        success_summary: typing.Text
        def __init__(self,
            *,
            service_name: typing.Text = ...,
            flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            success_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["flow",b"flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["flow",b"flow","service_name",b"service_name","success_summary",b"success_summary"]) -> None: ...

    class AllFlowsFail(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FAIL_FLOW_FIELD_NUMBER: builtins.int
        FAIL_SUMMARY_FIELD_NUMBER: builtins.int
        @property
        def fail_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        fail_summary: typing.Text
        def __init__(self,
            *,
            fail_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            fail_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["fail_flow",b"fail_flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["fail_flow",b"fail_flow","fail_summary",b"fail_summary"]) -> None: ...

    class SomeSourcesFail(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FAIL_FLOW_FIELD_NUMBER: builtins.int
        FAIL_SUMMARY_FIELD_NUMBER: builtins.int
        SUCCESS_FLOW_FIELD_NUMBER: builtins.int
        SUCCESS_SUMMARY_FIELD_NUMBER: builtins.int
        @property
        def fail_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        fail_summary: typing.Text
        @property
        def success_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        success_summary: typing.Text
        def __init__(self,
            *,
            fail_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            fail_summary: typing.Text = ...,
            success_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            success_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["fail_flow",b"fail_flow","success_flow",b"success_flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["fail_flow",b"fail_flow","fail_summary",b"fail_summary","success_flow",b"success_flow","success_summary",b"success_summary"]) -> None: ...

    class SomeFlowsFail(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FAIL_FLOW_FIELD_NUMBER: builtins.int
        FAIL_SUMMARY_FIELD_NUMBER: builtins.int
        SUCCESS_FLOW_FIELD_NUMBER: builtins.int
        SUCCESS_SUMMARY_FIELD_NUMBER: builtins.int
        @property
        def fail_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        fail_summary: typing.Text
        @property
        def success_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        success_summary: typing.Text
        def __init__(self,
            *,
            fail_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            fail_summary: typing.Text = ...,
            success_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            success_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["fail_flow",b"fail_flow","success_flow",b"success_flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["fail_flow",b"fail_flow","fail_summary",b"fail_summary","success_flow",b"success_flow","success_summary",b"success_summary"]) -> None: ...

    class SomePathsFail(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        INCONSISTENT_FLOW_FIELD_NUMBER: builtins.int
        FAIL_SUMMARY_FIELD_NUMBER: builtins.int
        SUCCESS_SUMMARY_FIELD_NUMBER: builtins.int
        @property
        def inconsistent_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        fail_summary: typing.Text
        success_summary: typing.Text
        def __init__(self,
            *,
            inconsistent_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            fail_summary: typing.Text = ...,
            success_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["inconsistent_flow",b"inconsistent_flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["fail_summary",b"fail_summary","inconsistent_flow",b"inconsistent_flow","success_summary",b"success_summary"]) -> None: ...

    VIOLATORS_FIELD_NUMBER: builtins.int
    VIOLATOR_DESCRIPTIONS_FIELD_NUMBER: builtins.int
    CONFORMERS_FIELD_NUMBER: builtins.int
    @property
    def violators(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServiceAccessibilityAssertionResult.Violator]: ...
    @property
    def violator_descriptions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def conformers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServiceAccessibilityAssertionResult.Conformer]: ...
    def __init__(self,
        *,
        violators: typing.Optional[typing.Iterable[global___ServiceAccessibilityAssertionResult.Violator]] = ...,
        violator_descriptions: typing.Optional[typing.Iterable[typing.Text]] = ...,
        conformers: typing.Optional[typing.Iterable[global___ServiceAccessibilityAssertionResult.Conformer]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["conformers",b"conformers","violator_descriptions",b"violator_descriptions","violators",b"violators"]) -> None: ...
global___ServiceAccessibilityAssertionResult = ServiceAccessibilityAssertionResult

class ServiceProtectionAssertionInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOURCE_FIELD_NUMBER: builtins.int
    SERVICES_FIELD_NUMBER: builtins.int
    SOURCE_GROUPS_FIELD_NUMBER: builtins.int
    @property
    def source(self) -> global___SourceExpr: ...
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServiceExpr]: ...
    @property
    def source_groups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SourceGroup]: ...
    def __init__(self,
        *,
        source: typing.Optional[global___SourceExpr] = ...,
        services: typing.Optional[typing.Iterable[global___ServiceExpr]] = ...,
        source_groups: typing.Optional[typing.Iterable[global___SourceGroup]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["source",b"source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["services",b"services","source",b"source","source_groups",b"source_groups"]) -> None: ...
global___ServiceProtectionAssertionInput = ServiceProtectionAssertionInput

class ServiceProtectionAssertionResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Violator(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SERVICE_NAME_FIELD_NUMBER: builtins.int
        DESCRIPTION_INDEX_FIELD_NUMBER: builtins.int
        ALL_FLOWS_ALLOWED_FIELD_NUMBER: builtins.int
        SOME_SOURCES_ALLOWED_FIELD_NUMBER: builtins.int
        SOME_FLOWS_ALLOWED_FIELD_NUMBER: builtins.int
        SOME_PATHS_ALLOWED_FIELD_NUMBER: builtins.int
        service_name: typing.Text
        @property
        def description_index(self) -> intentionet.bfe.proto.assertions.violations_pb2.DescriptionIndex: ...
        @property
        def all_flows_allowed(self) -> global___ServiceProtectionAssertionResult.AllFlowsAllowed: ...
        @property
        def some_sources_allowed(self) -> global___ServiceProtectionAssertionResult.SomeSourcesAllowed: ...
        @property
        def some_flows_allowed(self) -> global___ServiceProtectionAssertionResult.SomeFlowsAllowed: ...
        @property
        def some_paths_allowed(self) -> global___ServiceProtectionAssertionResult.SomePathsAllowed: ...
        def __init__(self,
            *,
            service_name: typing.Text = ...,
            description_index: typing.Optional[intentionet.bfe.proto.assertions.violations_pb2.DescriptionIndex] = ...,
            all_flows_allowed: typing.Optional[global___ServiceProtectionAssertionResult.AllFlowsAllowed] = ...,
            some_sources_allowed: typing.Optional[global___ServiceProtectionAssertionResult.SomeSourcesAllowed] = ...,
            some_flows_allowed: typing.Optional[global___ServiceProtectionAssertionResult.SomeFlowsAllowed] = ...,
            some_paths_allowed: typing.Optional[global___ServiceProtectionAssertionResult.SomePathsAllowed] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["all_flows_allowed",b"all_flows_allowed","description_index",b"description_index","problem",b"problem","some_flows_allowed",b"some_flows_allowed","some_paths_allowed",b"some_paths_allowed","some_sources_allowed",b"some_sources_allowed"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["all_flows_allowed",b"all_flows_allowed","description_index",b"description_index","problem",b"problem","service_name",b"service_name","some_flows_allowed",b"some_flows_allowed","some_paths_allowed",b"some_paths_allowed","some_sources_allowed",b"some_sources_allowed"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["problem",b"problem"]) -> typing.Optional[typing_extensions.Literal["all_flows_allowed","some_sources_allowed","some_flows_allowed","some_paths_allowed"]]: ...

    class Conformer(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SERVICE_NAME_FIELD_NUMBER: builtins.int
        FLOW_FIELD_NUMBER: builtins.int
        BLOCKED_SUMMARY_FIELD_NUMBER: builtins.int
        service_name: typing.Text
        @property
        def flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        blocked_summary: typing.Text
        def __init__(self,
            *,
            service_name: typing.Text = ...,
            flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            blocked_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["flow",b"flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["blocked_summary",b"blocked_summary","flow",b"flow","service_name",b"service_name"]) -> None: ...

    class AllFlowsAllowed(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ALLOWED_FLOW_FIELD_NUMBER: builtins.int
        ALLOWED_SUMMARY_FIELD_NUMBER: builtins.int
        @property
        def allowed_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        allowed_summary: typing.Text
        def __init__(self,
            *,
            allowed_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            allowed_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["allowed_flow",b"allowed_flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["allowed_flow",b"allowed_flow","allowed_summary",b"allowed_summary"]) -> None: ...

    class SomeSourcesAllowed(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ALLOWED_FLOW_FIELD_NUMBER: builtins.int
        ALLOWED_SUMMARY_FIELD_NUMBER: builtins.int
        BLOCKED_FLOW_FIELD_NUMBER: builtins.int
        BLOCKED_SUMMARY_FIELD_NUMBER: builtins.int
        @property
        def allowed_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        allowed_summary: typing.Text
        @property
        def blocked_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        blocked_summary: typing.Text
        def __init__(self,
            *,
            allowed_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            allowed_summary: typing.Text = ...,
            blocked_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            blocked_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["allowed_flow",b"allowed_flow","blocked_flow",b"blocked_flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["allowed_flow",b"allowed_flow","allowed_summary",b"allowed_summary","blocked_flow",b"blocked_flow","blocked_summary",b"blocked_summary"]) -> None: ...

    class SomeFlowsAllowed(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ALLOWED_FLOW_FIELD_NUMBER: builtins.int
        ALLOWED_SUMMARY_FIELD_NUMBER: builtins.int
        BLOCKED_FLOW_FIELD_NUMBER: builtins.int
        BLOCKED_SUMMARY_FIELD_NUMBER: builtins.int
        @property
        def allowed_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        allowed_summary: typing.Text
        @property
        def blocked_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        blocked_summary: typing.Text
        def __init__(self,
            *,
            allowed_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            allowed_summary: typing.Text = ...,
            blocked_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            blocked_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["allowed_flow",b"allowed_flow","blocked_flow",b"blocked_flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["allowed_flow",b"allowed_flow","allowed_summary",b"allowed_summary","blocked_flow",b"blocked_flow","blocked_summary",b"blocked_summary"]) -> None: ...

    class SomePathsAllowed(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        INCONSISTENT_FLOW_FIELD_NUMBER: builtins.int
        BLOCKED_SUMMARY_FIELD_NUMBER: builtins.int
        ALLOWED_SUMMARY_FIELD_NUMBER: builtins.int
        @property
        def inconsistent_flow(self) -> intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow: ...
        blocked_summary: typing.Text
        allowed_summary: typing.Text
        def __init__(self,
            *,
            inconsistent_flow: typing.Optional[intentionet.bfe.proto.assertions.flow_pb2.TracerouteParamsOrFlow] = ...,
            blocked_summary: typing.Text = ...,
            allowed_summary: typing.Text = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["inconsistent_flow",b"inconsistent_flow"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["allowed_summary",b"allowed_summary","blocked_summary",b"blocked_summary","inconsistent_flow",b"inconsistent_flow"]) -> None: ...

    VIOLATORS_FIELD_NUMBER: builtins.int
    VIOLATOR_DESCRIPTIONS_FIELD_NUMBER: builtins.int
    CONFORMERS_FIELD_NUMBER: builtins.int
    @property
    def violators(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServiceProtectionAssertionResult.Violator]: ...
    @property
    def violator_descriptions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def conformers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServiceProtectionAssertionResult.Conformer]: ...
    def __init__(self,
        *,
        violators: typing.Optional[typing.Iterable[global___ServiceProtectionAssertionResult.Violator]] = ...,
        violator_descriptions: typing.Optional[typing.Iterable[typing.Text]] = ...,
        conformers: typing.Optional[typing.Iterable[global___ServiceProtectionAssertionResult.Conformer]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["conformers",b"conformers","violator_descriptions",b"violator_descriptions","violators",b"violators"]) -> None: ...
global___ServiceProtectionAssertionResult = ServiceProtectionAssertionResult

class SourceGroup(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LOCATIONS_FIELD_NUMBER: builtins.int
    SOURCE_IPS_FIELD_NUMBER: builtins.int
    SOURCE_PORTS_FIELD_NUMBER: builtins.int
    @property
    def locations(self) -> global___Locations: ...
    @property
    def source_ips(self) -> global___SourceIps: ...
    @property
    def source_ports(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[intentionet.bfe.proto.datamodel.range_pb2.IntRange]: ...
    def __init__(self,
        *,
        locations: typing.Optional[global___Locations] = ...,
        source_ips: typing.Optional[global___SourceIps] = ...,
        source_ports: typing.Optional[typing.Iterable[intentionet.bfe.proto.datamodel.range_pb2.IntRange]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["locations",b"locations","source_ips",b"source_ips"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["locations",b"locations","source_ips",b"source_ips","source_ports",b"source_ports"]) -> None: ...
global___SourceGroup = SourceGroup

class Locations(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ORIGINATE_FIELD_NUMBER: builtins.int
    ENTER_FIELD_NUMBER: builtins.int
    @property
    def originate(self) -> global___Originate: ...
    @property
    def enter(self) -> global___Enter: ...
    def __init__(self,
        *,
        originate: typing.Optional[global___Originate] = ...,
        enter: typing.Optional[global___Enter] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["enter",b"enter","originate",b"originate","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["enter",b"enter","originate",b"originate","type",b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type",b"type"]) -> typing.Optional[typing_extensions.Literal["originate","enter"]]: ...
global___Locations = Locations

class Originate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INTERFACES_FIELD_NUMBER: builtins.int
    @property
    def interfaces(self) -> intentionet.bfe.proto.assertions.parameters_pb2.InterfaceFilterExpr: ...
    def __init__(self,
        *,
        interfaces: typing.Optional[intentionet.bfe.proto.assertions.parameters_pb2.InterfaceFilterExpr] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["interfaces",b"interfaces"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["interfaces",b"interfaces"]) -> None: ...
global___Originate = Originate

class Enter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INTERFACES_FIELD_NUMBER: builtins.int
    @property
    def interfaces(self) -> intentionet.bfe.proto.assertions.parameters_pb2.InterfaceFilterExpr: ...
    def __init__(self,
        *,
        interfaces: typing.Optional[intentionet.bfe.proto.assertions.parameters_pb2.InterfaceFilterExpr] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["interfaces",b"interfaces"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["interfaces",b"interfaces"]) -> None: ...
global___Enter = Enter

class SourceIps(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INCLUDE_FIELD_NUMBER: builtins.int
    EXCLUDE_FIELD_NUMBER: builtins.int
    @property
    def include(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[intentionet.bfe.proto.assertions.parameters_pb2.IpAddressFilterExpr]: ...
    @property
    def exclude(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[intentionet.bfe.proto.assertions.parameters_pb2.IpAddressFilterExpr]: ...
    def __init__(self,
        *,
        include: typing.Optional[typing.Iterable[intentionet.bfe.proto.assertions.parameters_pb2.IpAddressFilterExpr]] = ...,
        exclude: typing.Optional[typing.Iterable[intentionet.bfe.proto.assertions.parameters_pb2.IpAddressFilterExpr]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["exclude",b"exclude","include",b"include"]) -> None: ...
global___SourceIps = SourceIps

class ServiceExpr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SERVICE_IP_FIELD_NUMBER: builtins.int
    SERVICE_IPS_FIELD_NUMBER: builtins.int
    APPS_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def service_ip(self) -> intentionet.bfe.proto.assertions.parameters_pb2.IpAddressFilterExpr: ...
    @property
    def service_ips(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[intentionet.bfe.proto.assertions.parameters_pb2.IpAddressFilterExpr]: ...
    @property
    def apps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        name: typing.Text = ...,
        service_ip: typing.Optional[intentionet.bfe.proto.assertions.parameters_pb2.IpAddressFilterExpr] = ...,
        service_ips: typing.Optional[typing.Iterable[intentionet.bfe.proto.assertions.parameters_pb2.IpAddressFilterExpr]] = ...,
        apps: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["service_ip",b"service_ip"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["apps",b"apps","name",b"name","service_ip",b"service_ip","service_ips",b"service_ips"]) -> None: ...
global___ServiceExpr = ServiceExpr

class SourceExpr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LOCATION_FIELD_NUMBER: builtins.int
    SOURCE_IPS_FIELD_NUMBER: builtins.int
    SOURCE_PORTS_FIELD_NUMBER: builtins.int
    @property
    def location(self) -> global___LocationExpr: ...
    @property
    def source_ips(self) -> global___SourceIps: ...
    @property
    def source_ports(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[intentionet.bfe.proto.datamodel.range_pb2.IntRange]: ...
    def __init__(self,
        *,
        location: typing.Optional[global___LocationExpr] = ...,
        source_ips: typing.Optional[global___SourceIps] = ...,
        source_ports: typing.Optional[typing.Iterable[intentionet.bfe.proto.datamodel.range_pb2.IntRange]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["location",b"location","source_ips",b"source_ips"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["location",b"location","source_ips",b"source_ips","source_ports",b"source_ports"]) -> None: ...
global___SourceExpr = SourceExpr

class LocationExpr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INTERFACE_LOCATION_FIELD_NUMBER: builtins.int
    INTERFACE_LINK_LOCATION_FIELD_NUMBER: builtins.int
    @property
    def interface_location(self) -> global___InterfaceLocationExpr: ...
    @property
    def interface_link_location(self) -> global___InterfaceLinkLocationExpr: ...
    def __init__(self,
        *,
        interface_location: typing.Optional[global___InterfaceLocationExpr] = ...,
        interface_link_location: typing.Optional[global___InterfaceLinkLocationExpr] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["interface_link_location",b"interface_link_location","interface_location",b"interface_location","location",b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["interface_link_location",b"interface_link_location","interface_location",b"interface_location","location",b"location"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["location",b"location"]) -> typing.Optional[typing_extensions.Literal["interface_location","interface_link_location"]]: ...
global___LocationExpr = LocationExpr

class InterfaceLocationExpr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INTERFACE_FIELD_NUMBER: builtins.int
    @property
    def interface(self) -> intentionet.bfe.proto.assertions.parameters_pb2.InterfaceExpr: ...
    def __init__(self,
        *,
        interface: typing.Optional[intentionet.bfe.proto.assertions.parameters_pb2.InterfaceExpr] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["interface",b"interface"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["interface",b"interface"]) -> None: ...
global___InterfaceLocationExpr = InterfaceLocationExpr

class InterfaceLinkLocationExpr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INTERFACE_FIELD_NUMBER: builtins.int
    @property
    def interface(self) -> intentionet.bfe.proto.assertions.parameters_pb2.InterfaceExpr: ...
    def __init__(self,
        *,
        interface: typing.Optional[intentionet.bfe.proto.assertions.parameters_pb2.InterfaceExpr] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["interface",b"interface"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["interface",b"interface"]) -> None: ...
global___InterfaceLinkLocationExpr = InterfaceLinkLocationExpr
