
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-26T18:14:34+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "f4fc7707039cf428f85afa7d41fc67f40973891a",
 "version": "3.8.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
