# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intentionet/bfe/proto/datamodel/location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from intentionet.bfe.proto.datamodel import device_pb2 as intentionet_dot_bfe_dot_proto_dot_datamodel_dot_device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.intentionet/bfe/proto/datamodel/location.proto\x12\x19\x63om.intentionet.datamodel\x1a,intentionet/bfe/proto/datamodel/device.proto\"\xe1\x01\n\x08Location\x12]\n\x12interface_location\x18\x01 \x01(\x0b\x32,.com.intentionet.datamodel.InterfaceLocationH\x00R\x11interfaceLocation\x12j\n\x17interface_link_location\x18\x02 \x01(\x0b\x32\x30.com.intentionet.datamodel.InterfaceLinkLocationH\x00R\x15interfaceLinkLocationB\n\n\x08location\"W\n\x11InterfaceLocation\x12\x42\n\tinterface\x18\x01 \x01(\x0b\x32$.com.intentionet.datamodel.InterfaceR\tinterface\"[\n\x15InterfaceLinkLocation\x12\x42\n\tinterface\x18\x01 \x01(\x0b\x32$.com.intentionet.datamodel.InterfaceR\tinterfaceB\x02P\x01\x62\x06proto3')



_LOCATION = DESCRIPTOR.message_types_by_name['Location']
_INTERFACELOCATION = DESCRIPTOR.message_types_by_name['InterfaceLocation']
_INTERFACELINKLOCATION = DESCRIPTOR.message_types_by_name['InterfaceLinkLocation']
Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  'DESCRIPTOR' : _LOCATION,
  '__module__' : 'intentionet.bfe.proto.datamodel.location_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.datamodel.Location)
  })
_sym_db.RegisterMessage(Location)

InterfaceLocation = _reflection.GeneratedProtocolMessageType('InterfaceLocation', (_message.Message,), {
  'DESCRIPTOR' : _INTERFACELOCATION,
  '__module__' : 'intentionet.bfe.proto.datamodel.location_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.datamodel.InterfaceLocation)
  })
_sym_db.RegisterMessage(InterfaceLocation)

InterfaceLinkLocation = _reflection.GeneratedProtocolMessageType('InterfaceLinkLocation', (_message.Message,), {
  'DESCRIPTOR' : _INTERFACELINKLOCATION,
  '__module__' : 'intentionet.bfe.proto.datamodel.location_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.datamodel.InterfaceLinkLocation)
  })
_sym_db.RegisterMessage(InterfaceLinkLocation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _LOCATION._serialized_start=124
  _LOCATION._serialized_end=349
  _INTERFACELOCATION._serialized_start=351
  _INTERFACELOCATION._serialized_end=438
  _INTERFACELINKLOCATION._serialized_start=440
  _INTERFACELINKLOCATION._serialized_end=531
# @@protoc_insertion_point(module_scope)
