
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-21T20:23:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac06f8cc691c62e3d56e9e94ef015a675c73851f",
 "version": "0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
