
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-27T14:30:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f25c16118e971525133053584f149001371fbf5",
 "version": "v4.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
