
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-20T13:39:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "890507ff4913d713a9bf2ec96c47e543151a5f90",
 "version": "1.12.53"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
