
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-26T16:02:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "28ec521a23a75b90490103cf3821a58c3db1af40",
 "version": "0.2.15.post0.dev27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
