from .. import utils as utils
from ..core.formatter import FormattedEntity as FormattedEntity
from .base import Worker as Worker
from _typeshed import Incomplete

class Subprocess(FormattedEntity, Worker):
    params: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    create_subprocess: Incomplete
    async def init(self): ...
    @property
    def process(self): ...
    def make_command(self, value): ...
    async def run_cmd(self, *args, **kwargs): ...
    async def work(self): ...
    async def start(self): ...
    async def stop(self, force: bool = ...) -> None: ...
