"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class FileParseStatusAnswer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Row(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FILE_NAME_FIELD_NUMBER: builtins.int
        NODES_FIELD_NUMBER: builtins.int
        file_name: typing.Text
        @property
        def nodes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
        def __init__(self,
            *,
            file_name: typing.Text = ...,
            nodes: typing.Optional[typing.Iterable[typing.Text]] = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["file_name",b"file_name","nodes",b"nodes"]) -> None: ...

    ROWS_FIELD_NUMBER: builtins.int
    @property
    def rows(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FileParseStatusAnswer.Row]: ...
    def __init__(self,
        *,
        rows: typing.Optional[typing.Iterable[global___FileParseStatusAnswer.Row]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["rows",b"rows"]) -> None: ...
global___FileParseStatusAnswer = FileParseStatusAnswer
