
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-21T19:36:43+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "61c738bf0f65c3da83166000257bbb04231f7c32",
 "version": "3.8.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
