from . import config as config, formatter as formatter
from _typeshed import Incomplete
from typing import Dict, Iterable, Optional

logger: Incomplete

def load_plugin(module: str, force: bool = ..., *, cache: Dict = ...) -> Optional['Plugin']: ...
def get_names() -> Iterable[str]: ...
def search_plugins(*modules, force: bool = ...): ...

class Plugin:
    formatters: Incomplete
    config_loaders: Incomplete
    configs: Incomplete
    def __init__(self) -> None: ...
    def get_config(self): ...
    def add_arguments(self, parser) -> None: ...
    def parse_known_args(self, args, namespace): ...

class ProxyPlugin(Plugin):
    configs: Incomplete
    def __init__(self, original) -> None: ...
