
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-22T20:27:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a4a35c7697879b27ceeb4d882ed9c914c91214c",
 "version": "2.7.8.dev20220723"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
