
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-21T08:57:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b43b4d4d44d1db5b4f9b96b6d758d7ee886ac83d",
 "version": "2.0.0b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
