# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intentionet/bfe/proto/traceroute/traceroute.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1intentionet/bfe/proto/traceroute/traceroute.proto\x12$com.intentionet.bfe.proto.traceroute\x1a\x1egoogle/protobuf/wrappers.proto\"\xcd\x06\n\x14TracerouteToolParams\x12\x30\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValueR\x04\x66rom\x12\x39\n\tsource_ip\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueR\x08sourceIp\x12,\n\x02to\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValueR\x02to\x12.\n\x03\x61pp\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValueR\x03\x61pp\x12@\n\rbidirectional\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\rbidirectional\x12=\n\x0bsource_port\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueR\nsourcePort\x12\x30\n\x04\x64scp\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueR\x04\x64scp\x12.\n\x03\x65\x63n\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueR\x03\x65\x63n\x12\x45\n\x0f\x66ragment_offset\x18\t \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueR\x0e\x66ragmentOffset\x12\x41\n\rpacket_length\x18\n \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueR\x0cpacketLength\x12`\n\ttcp_flags\x18\x0b \x01(\x0b\x32\x43.com.intentionet.bfe.proto.traceroute.TracerouteToolParams.TcpFlagsR\x08tcpFlags\x1a\x9a\x01\n\x08TcpFlags\x12\x10\n\x03syn\x18\x01 \x01(\x08R\x03syn\x12\x10\n\x03\x61\x63k\x18\x02 \x01(\x08R\x03\x61\x63k\x12\x10\n\x03rst\x18\x03 \x01(\x08R\x03rst\x12\x10\n\x03psh\x18\x04 \x01(\x08R\x03psh\x12\x10\n\x03urg\x18\x05 \x01(\x08R\x03urg\x12\x10\n\x03\x66in\x18\x06 \x01(\x08R\x03\x66in\x12\x10\n\x03\x65\x63\x65\x18\x07 \x01(\x08R\x03\x65\x63\x65\x12\x10\n\x03\x63wr\x18\x08 \x01(\x08R\x03\x63wrBN\n$com.intentionet.bfe.proto.tracerouteP\x01Z$intentionet.com/bfe/proto/tracerouteb\x06proto3')



_TRACEROUTETOOLPARAMS = DESCRIPTOR.message_types_by_name['TracerouteToolParams']
_TRACEROUTETOOLPARAMS_TCPFLAGS = _TRACEROUTETOOLPARAMS.nested_types_by_name['TcpFlags']
TracerouteToolParams = _reflection.GeneratedProtocolMessageType('TracerouteToolParams', (_message.Message,), {

  'TcpFlags' : _reflection.GeneratedProtocolMessageType('TcpFlags', (_message.Message,), {
    'DESCRIPTOR' : _TRACEROUTETOOLPARAMS_TCPFLAGS,
    '__module__' : 'intentionet.bfe.proto.traceroute.traceroute_pb2'
    # @@protoc_insertion_point(class_scope:com.intentionet.bfe.proto.traceroute.TracerouteToolParams.TcpFlags)
    })
  ,
  'DESCRIPTOR' : _TRACEROUTETOOLPARAMS,
  '__module__' : 'intentionet.bfe.proto.traceroute.traceroute_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.bfe.proto.traceroute.TracerouteToolParams)
  })
_sym_db.RegisterMessage(TracerouteToolParams)
_sym_db.RegisterMessage(TracerouteToolParams.TcpFlags)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.intentionet.bfe.proto.tracerouteP\001Z$intentionet.com/bfe/proto/traceroute'
  _TRACEROUTETOOLPARAMS._serialized_start=124
  _TRACEROUTETOOLPARAMS._serialized_end=969
  _TRACEROUTETOOLPARAMS_TCPFLAGS._serialized_start=815
  _TRACEROUTETOOLPARAMS_TCPFLAGS._serialized_end=969
# @@protoc_insertion_point(module_scope)
