
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-27T12:44:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "29889eb45144dfeae7a4ed2cfdb8a84dcb16c11f",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
