"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import intentionet.bfe.proto.change_validation.change_validation_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class PreviewId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UID_FIELD_NUMBER: builtins.int
    uid: typing.Text
    def __init__(self,
        *,
        uid: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uid",b"uid"]) -> None: ...
global___PreviewId = PreviewId

class CreateStepPreviewRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHANGE_REVIEW_ID_FIELD_NUMBER: builtins.int
    STEP_FIELD_NUMBER: builtins.int
    @property
    def change_review_id(self) -> intentionet.bfe.proto.change_validation.change_validation_pb2.ChangeReviewId: ...
    @property
    def step(self) -> intentionet.bfe.proto.change_validation.change_validation_pb2.Step: ...
    def __init__(self,
        *,
        change_review_id: typing.Optional[intentionet.bfe.proto.change_validation.change_validation_pb2.ChangeReviewId] = ...,
        step: typing.Optional[intentionet.bfe.proto.change_validation.change_validation_pb2.Step] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["change_review_id",b"change_review_id","step",b"step"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["change_review_id",b"change_review_id","step",b"step"]) -> None: ...
global___CreateStepPreviewRequest = CreateStepPreviewRequest

class CreateStepPreviewResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PREVIEW_ID_FIELD_NUMBER: builtins.int
    @property
    def preview_id(self) -> global___PreviewId: ...
    def __init__(self,
        *,
        preview_id: typing.Optional[global___PreviewId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id"]) -> None: ...
global___CreateStepPreviewResponse = CreateStepPreviewResponse

class UpdateStepPreviewRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PREVIEW_ID_FIELD_NUMBER: builtins.int
    STEP_FIELD_NUMBER: builtins.int
    @property
    def preview_id(self) -> global___PreviewId: ...
    @property
    def step(self) -> intentionet.bfe.proto.change_validation.change_validation_pb2.Step: ...
    def __init__(self,
        *,
        preview_id: typing.Optional[global___PreviewId] = ...,
        step: typing.Optional[intentionet.bfe.proto.change_validation.change_validation_pb2.Step] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id","step",b"step"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id","step",b"step"]) -> None: ...
global___UpdateStepPreviewRequest = UpdateStepPreviewRequest

class UpdateStepPreviewResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___UpdateStepPreviewResponse = UpdateStepPreviewResponse

class DeleteStepPreviewRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PREVIEW_ID_FIELD_NUMBER: builtins.int
    @property
    def preview_id(self) -> global___PreviewId: ...
    def __init__(self,
        *,
        preview_id: typing.Optional[global___PreviewId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id"]) -> None: ...
global___DeleteStepPreviewRequest = DeleteStepPreviewRequest

class DeleteStepPreviewResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___DeleteStepPreviewResponse = DeleteStepPreviewResponse

class GetStepPreviewResultRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PREVIEW_ID_FIELD_NUMBER: builtins.int
    @property
    def preview_id(self) -> global___PreviewId: ...
    def __init__(self,
        *,
        preview_id: typing.Optional[global___PreviewId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id"]) -> None: ...
global___GetStepPreviewResultRequest = GetStepPreviewResultRequest

class GetStepPreviewResultResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    status: intentionet.bfe.proto.change_validation.change_validation_pb2.StepStatus.ValueType
    @property
    def result(self) -> intentionet.bfe.proto.change_validation.change_validation_pb2.StepResult: ...
    def __init__(self,
        *,
        status: intentionet.bfe.proto.change_validation.change_validation_pb2.StepStatus.ValueType = ...,
        result: typing.Optional[intentionet.bfe.proto.change_validation.change_validation_pb2.StepResult] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result","status",b"status"]) -> None: ...
global___GetStepPreviewResultResponse = GetStepPreviewResultResponse

class CommitStepPreviewRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PREVIEW_ID_FIELD_NUMBER: builtins.int
    STEP_ID_FIELD_NUMBER: builtins.int
    @property
    def preview_id(self) -> global___PreviewId: ...
    @property
    def step_id(self) -> intentionet.bfe.proto.change_validation.change_validation_pb2.StepId: ...
    def __init__(self,
        *,
        preview_id: typing.Optional[global___PreviewId] = ...,
        step_id: typing.Optional[intentionet.bfe.proto.change_validation.change_validation_pb2.StepId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id","step_id",b"step_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["preview_id",b"preview_id","step_id",b"step_id"]) -> None: ...
global___CommitStepPreviewRequest = CommitStepPreviewRequest

class CommitStepPreviewResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STEP_ID_FIELD_NUMBER: builtins.int
    @property
    def step_id(self) -> intentionet.bfe.proto.change_validation.change_validation_pb2.StepId: ...
    def __init__(self,
        *,
        step_id: typing.Optional[intentionet.bfe.proto.change_validation.change_validation_pb2.StepId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["step_id",b"step_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["step_id",b"step_id"]) -> None: ...
global___CommitStepPreviewResponse = CommitStepPreviewResponse
