SPARSITY_THRESHOLD = 0.98
K_NO_PAYTV = 30
K_PAYTV = 26
MINIBATCH_SIZE = 6
MIN_MEMBER_COUNT = 15
TENDENCY_CUTOFF = 3
ENSEMBLE_SD_CUTOFF = 5
TOP_N_MEMBERS_COUNT = 5

GENDER_MAP = {
    0: -1,
    "na": -1,
    "nan": -1,
    "m": 0,
    "f": 1
}
