# Generated by Django 2.2.26 on 2022-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hiphopcommunity', '0016_auto_20220426_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='contact',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Url de contact'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='contact',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Url de contact'),
        ),
    ]
