from pathlib import Path

PROJECT_DIR = Path(__file__).parent.parent
TESTS_DIR = PROJECT_DIR / "tests"

INPUT_FILES_DIR = TESTS_DIR / "input_files"
REQUIREMENTS_IN_PATH = INPUT_FILES_DIR / "requirements.in"
REQUIREMENTS_OUT_PATH = INPUT_FILES_DIR / "requirements.txt"
REQUIREMENTS_MULTIPLATFORM_DIR = INPUT_FILES_DIR / "multi-platform"
REQUIREMENTS_MULTIPLATFORM_OUT_PATH = (
    REQUIREMENTS_MULTIPLATFORM_DIR / "requirements-3.7-win32.txt"
)
REQUIREMENTS_MULTIPLATFORM_CONFIG_PATH = REQUIREMENTS_MULTIPLATFORM_DIR / "mvenv.yaml"
BASIC_CONFIG_PATH = INPUT_FILES_DIR / "mvenv.yaml"
