
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-01T16:13:19+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "75e7b85dc048ad00a84379012d44f40aa8b09d09",
 "version": "4.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
