"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import intentionet.bfe.proto.datamodel.flow_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LocationType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _LocationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LocationType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOCATION_TYPE_INTERFACE: _LocationType.ValueType  # 0
    LOCATION_TYPE_INTERFACE_LINK: _LocationType.ValueType  # 1
class LocationType(_LocationType, metaclass=_LocationTypeEnumTypeWrapper):
    pass

LOCATION_TYPE_INTERFACE: LocationType.ValueType  # 0
LOCATION_TYPE_INTERFACE_LINK: LocationType.ValueType  # 1
global___LocationType = LocationType


class ReachabilityHeatMap(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENTRIES_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Entry]: ...
    @property
    def metadata(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Metadata]: ...
    def __init__(self,
        *,
        entries: typing.Optional[typing.Iterable[global___Entry]] = ...,
        metadata: typing.Optional[typing.Iterable[global___Metadata]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries",b"entries","metadata",b"metadata"]) -> None: ...
global___ReachabilityHeatMap = ReachabilityHeatMap

class Entry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SRC_FIELD_NUMBER: builtins.int
    DST_FIELD_NUMBER: builtins.int
    INC_DETAILS_FIELD_NUMBER: builtins.int
    DEC_DETAILS_FIELD_NUMBER: builtins.int
    src: builtins.int
    dst: builtins.int
    @property
    def inc_details(self) -> global___EntryDetails: ...
    @property
    def dec_details(self) -> global___EntryDetails: ...
    def __init__(self,
        *,
        src: builtins.int = ...,
        dst: builtins.int = ...,
        inc_details: typing.Optional[global___EntryDetails] = ...,
        dec_details: typing.Optional[global___EntryDetails] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dec_details",b"dec_details","inc_details",b"inc_details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dec_details",b"dec_details","dst",b"dst","inc_details",b"inc_details","src",b"src"]) -> None: ...
global___Entry = Entry

class EntryDetails(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEAT_FIELD_NUMBER: builtins.int
    IP_PROTOCOLS_FIELD_NUMBER: builtins.int
    TCP_DST_PORTS_FIELD_NUMBER: builtins.int
    UDP_DST_PORTS_FIELD_NUMBER: builtins.int
    ICMP_TYPES_FIELD_NUMBER: builtins.int
    SRC_IPS_FIELD_NUMBER: builtins.int
    DST_IPS_FIELD_NUMBER: builtins.int
    REPRESENTATIVE_FLOW_FIELD_NUMBER: builtins.int
    heat: builtins.float
    ip_protocols: typing.Text
    tcp_dst_ports: typing.Text
    udp_dst_ports: typing.Text
    icmp_types: typing.Text
    @property
    def src_ips(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def dst_ips(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def representative_flow(self) -> intentionet.bfe.proto.datamodel.flow_pb2.Flow: ...
    def __init__(self,
        *,
        heat: builtins.float = ...,
        ip_protocols: typing.Text = ...,
        tcp_dst_ports: typing.Text = ...,
        udp_dst_ports: typing.Text = ...,
        icmp_types: typing.Text = ...,
        src_ips: typing.Optional[typing.Iterable[typing.Text]] = ...,
        dst_ips: typing.Optional[typing.Iterable[typing.Text]] = ...,
        representative_flow: typing.Optional[intentionet.bfe.proto.datamodel.flow_pb2.Flow] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["representative_flow",b"representative_flow"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dst_ips",b"dst_ips","heat",b"heat","icmp_types",b"icmp_types","ip_protocols",b"ip_protocols","representative_flow",b"representative_flow","src_ips",b"src_ips","tcp_dst_ports",b"tcp_dst_ports","udp_dst_ports",b"udp_dst_ports"]) -> None: ...
global___EntryDetails = EntryDetails

class Metadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    LOCATIONS_FIELD_NUMBER: builtins.int
    SRC_PARENT_FIELD_NUMBER: builtins.int
    DST_PARENT_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def locations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HeatmapLocation]: ...
    @property
    def src_parent(self) -> global___Parent: ...
    @property
    def dst_parent(self) -> global___Parent: ...
    def __init__(self,
        *,
        name: typing.Text = ...,
        locations: typing.Optional[typing.Iterable[global___HeatmapLocation]] = ...,
        src_parent: typing.Optional[global___Parent] = ...,
        dst_parent: typing.Optional[global___Parent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dst_parent",b"dst_parent","src_parent",b"src_parent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dst_parent",b"dst_parent","locations",b"locations","name",b"name","src_parent",b"src_parent"]) -> None: ...
global___Metadata = Metadata

class HeatmapLocation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_FIELD_NUMBER: builtins.int
    NODE_FIELD_NUMBER: builtins.int
    INTERFACE_FIELD_NUMBER: builtins.int
    type: global___LocationType.ValueType
    node: typing.Text
    interface: typing.Text
    def __init__(self,
        *,
        type: global___LocationType.ValueType = ...,
        node: typing.Text = ...,
        interface: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["interface",b"interface","node",b"node","type",b"type"]) -> None: ...
global___HeatmapLocation = HeatmapLocation

class Parent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(self,
        *,
        id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___Parent = Parent
