
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-20T19:38:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "05aca707da69e3ccd3b92ee1ff4674b92e068746",
 "version": "0.2.14.post0.dev44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
