
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-21T14:04:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0320a6a4f0cb83d2dc811671bd3a3e8c63596949",
 "version": "2.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
