
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-21T12:11:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "37b4f5c2cde86e611993abfd5b739690e97ec069",
 "version": "2.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
