
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-22T07:44:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a2bbd548ed7c4abbb7fbc49d225f6492255463e",
 "version": "v0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
